name:                the-shit
version:             0.1.0.0
github:              "elisabethstenholm/the-shit"
license:             MIT
author:              "Elisabeth Stenholm"
maintainer:          "elisabeth@stenholm.one"
copyright:           "2024 Elisabeth Stenholm"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elisabethstenholm/the-shit#readme>

dependencies:
- base >= 4.7 && < 5
- extra >= 1.7.16
- optparse-applicative >= 0.18.1.0
- req >= 3.13.2
- aeson >= 2.1.2.1
- text >= 2.0.2
- bytestring >= 0.11.5.3
- ansi-terminal >= 1.0.2
- microlens-platform >= 0.4.3.5
- microlens-aeson >= 2.5.2
- process >= 1.6.19.0
- terminfo >= 0.4.1.6
- applicative-logic >= 0.1.0.2
- text-format >= 0.3.2.1
- unix >= 2.8.4.0
- process >= 1.6.19.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  the-shit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-shit

tests:
  the-shit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-shit
