name:                the-fix
version:             0.1.0.0
github:              "elisabethstenholm/the-fix"
license:             MIT
author:              "Elisabeth Stenholm"
maintainer:          "elisabeth@stenholm.one"
copyright:           "2024 Elisabeth Stenholm"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elisabethstenholm/the-fix#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.18.1.0
- req >= 3.13.2
- aeson >= 2.1.2.1
- text >= 2.0.2
- bytestring >= 0.11.5.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  the-fix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-fix

tests:
  the-fix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - the-fix
